# Auto-generated from .repo.toml by 'just repo_toml_generate'
# DO NOT EDIT THIS FILE MANUALLY - regenerate with: just repo_toml_generate

# About section
REPO_DESCRIPTION="Google+ Posts dumper into Markdown"
REPO_LICENSE=""
REPO_TOPICS="blog,blogging,google-plus,html-to-markdown,html-to-markdown-converter,hugo,markdown"

# URLs section
REPO_GIT_SSH="git@github.com:chicks-net/google-plus-posts-dumper.git"
REPO_WEB_URL="https://github.com/chicks-net/google-plus-posts-dumper"

# Derived values
REPO_ORG_NAME="chicks-net"
REPO_REPO_NAME="google-plus-posts-dumper"

# Feature flags (strings: "true" or "false")
FLAG_CLAUDE="true"
FLAG_CLAUDE_REVIEW="true"
FLAG_COPILOT_REVIEW="true"
FLAG_STANDARD_RELEASE="true"

# Topics as array (for iteration)
REPO_TOPICS_ARRAY=(
    "blog"
    "blogging"
    "google-plus"
    "html-to-markdown"
    "html-to-markdown-converter"
    "hugo"
    "markdown"
)
